services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Afpa1234
      MYSQL_INNODB_FORCE_RECOVERY: 1
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306

    networks:
      - cda_network

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    networks:
      - cda_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
    networks:
      - cda_network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - cda_network

volumes:
  data:
    driver: local

networks:
  cda_network:
    driver: bridge


